approvers/site

.eslintrc.json, .prettierrc.json, package.json, src/components/button.tsx, src/components/card.tsx, src/components/date.tsx, src/components/header.tsx, src/components/layout.tsx, src/components/paper.tsx, src/components/sns-link.tsx, src/lib/blog-fetch.ts, src/lib/member-fetch.ts, src/pages/blog.tsx, src/pages/blog/[id].tsx, src/pages/index.tsx, src/pages/join.tsx, src/pages/member.tsx, yarn.lock
LinterとFormatterを導入した。また、Git Hooksを利用し、コミット時に自動的に適用されるようにした。
- ESLintの導入
- Prettierの導入
- Huskyの導入
- Lint Stagedの導入
=> build: LinterとFormatterの導入

.github/workflows/workflow.yml, package.json
=> ci: setup github actions

data/members/list.yaml
- Lockdef さんを追加
- pro を ガチプロ に更新
=> メンバーリストの更新

src/components/layout.tsx, src/pages/blog.tsx, src/pages/blog/[id].tsx, src/pages/index.tsx, src/pages/join.tsx, src/pages/member.tsx
#8 への対応で、
`Layout` コンポーネント経由で各ページにタイトルを追加しました
=> タイトルを追加 (#8 の対応)

src/components/button.tsx
=> ビルドにこけるので ShadowButton を修正

README.md
英字の大文字・小文字は，用法・容量を守り，正しく使用しましょう．
=> 💬 SASS -> Sass

src/components/layout.tsx
以下のことを行いました
- #18 の対応
- `og` 系の `meta` の追加
- `description`、`name、`image` の `meta` の追加
=> Twitter のカードなどを実装

.github/workflows/workflow.yml
GitHub ActionsのDeployジョブにCNAMEの設定を追加した。
=> ci: CNAME設定の追加

src/sass/pages/member.module.sass
ローカルで試したらこれで治った
svgってfont-sizeで大きさ調整するものだっけ？
=> アイコンのサイズがおかしいのを修正

.github/workflows/workflow.yml, next-env.d.ts, next.config.js, src/lib/gtag.ts, src/pages/_app.tsx, src/pages/_document.tsx
Google Analyticsを追加したよ
環境変数`GOOGLE_ANALYTICS_ID`を追加してビルドすればそれが適用されるよ
これ見てやりました: https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics
resolve #55
=> Google Analyticsを追加したよ

.github/workflows/deploy.yml
CI改善時に環境変数を注入する処理を書き忘れてました。
*生きててごめんなさい*
=> CIに環境変数入れ忘れてた

package.json, postcss.config.json, src/scss/global.scss, yarn.lock
Autoprefixer がこれだけで使えます
- :sparkles: Add postcss.config.json
- :fire: Remove an extra pefix
=> PostCSS コンフィグの追加

src/components/button.tsx, src/components/date.tsx, src/components/paper.tsx, src/components/questions.tsx, src/pages/blog.tsx, src/pages/member.tsx, src/scss/_color.variable.scss, src/scss/_details.variable.scss, src/scss/components/button.module.scss, src/scss/components/date.module.scss, src/scss/components/external-link.module.scss, src/scss/components/footer.module.scss, src/scss/components/header.module.scss, src/scss/components/paper.module.scss, src/scss/components/questions.module.scss, src/scss/components/sns-link.module.scss, src/scss/components/triangle.module.scss, src/scss/global.scss, src/scss/pages/blog.module.scss, src/scss/pages/index.module.scss, src/scss/pages/join.module.scss, src/scss/pages/member.module.scss, src/scss/pages/policy.module.scss, src/scss/wrapper.module.scss
=> テーマとレイアウトの分離リファクタ

src/components/date.tsx, src/components/external-link.tsx, src/components/footer.tsx, src/components/header.tsx, src/components/layout.tsx, src/components/paper.tsx, src/components/questions.tsx, src/components/sns-link.tsx, src/pages/_app.tsx, src/pages/blog.tsx, src/pages/blog/[id].tsx, src/pages/index.tsx, src/pages/join.tsx, src/pages/member.tsx, src/pages/policy.tsx
=> 🎨 Use import type

data/members/list.yaml
=> feat: update some member role

data/members/list.yaml
しばらく隠れます。思うツボになってしまっている感じがしますが、引責ということで。
私ではないもう一方もサーバーから脱退しています。確認してください。
=> 💬 Updated Member List

src/components/external-link.tsx, src/components/sns-link.tsx, src/scss/components/external-link.module.scss, src/scss/pages/member.module.scss
- 💄 Specify flex to fix aligning vertical
- ✨ Add ExternalIconLink
=> 読込中にアイコンが巨大化するグリッチを修正

src/scss/pages/member.module.scss, src/scss/wrapper.module.scss
=> アイコンが上段揃えになるように変更

src/pages/blog.tsx, src/scss/pages/blog.module.scss
=> ブログ一覧の画像サイズの修正

src/scss/global.scss
- 💄 Fix selection color into not fore but back
=> 選択色が背景になるように修正

src/components/header.tsx, src/components/layout.tsx, src/components/questions.tsx, src/lib/member-fetch.ts, src/pages/member.tsx
- 🎨 Split Links
- 🎨 Add readonly
- 🎨 Split  components for metas
- 🎨 Split questionAnswers
- 🎨 Refactor validateMember, add validateSNSLinks
- 🎨 Use function
- 🎨 Add readonly
- 🐛 Fix a validation
=> スクリプト細部のリファクタ

.github/workflows/ci.yml, .github/workflows/deploy.yml
Closes #142.
GitHub Actionsの該当ブランチ名の更新です。
=> Update branch names in workflows

src/lib/blog-fetch.ts, src/pages/blog/[id].tsx
- fix: Add lastUpdate Static generation of blog posts may fail by static props didn't change
- fix: Fix path resolving
=> ブログ記事の Markdown ファイルの更新が反映されないバグの修正

data/blogs/001.md, src/lib/blog-fetch.ts, src/pages/blog.tsx, src/pages/blog/[id].tsx
この PR をマージする前に, site-data のすべてのブログ記事 Markdown の frontmatter へ author を追加してください.
- feat: Add author field
- feat: Add author text
=> ブログに作者名を追加

src/lib/blog-fetch.ts
deploy CI のビルドにだけ失敗するという怪奇現象が起こっているため, とりあえずログ出力を追加してどうなっているか見てみるための PR です.
=> デバッグのためのログ追加

src/components/paper.tsx, src/pages/member.tsx, src/scss/components/paper.module.scss
=> Grid の追加による Paper のリファクタ

src/lib/blog-fetch.ts
=> ブログ取得のリファクタ

src/lib/blog-fetch.ts
string による指定もこれまで通り使えますし,
不正な日付文字列の検査のバグも修正しています.
=> ブログの作成日の date 型サポート

src/components/header.tsx, src/pages/blog/[id].tsx, src/scss/components/button.module.scss
- ヘッダーのナビゲーションのリンクボタンにて, Next.js の `Link`
の使い方を間違えていた部分を修正しました.
- 上のボタン全体のコンテナ要素を
`div` から `nav` に変更しました.
- ブログ記事コンテナ要素を `div` から `article` に変更しました.
- ブロク記事のタイトルと日付部分を `header` に格納するようにしました.
=> アクセシビリティに関する修正

src/scss/pages/blog.module.scss
=> flex-shrink の追加によるアイコンサイズ変化の抑制

src/components/prev-next-link.tsx, src/lib/blog-fetch.ts, src/pages/blog/[id].tsx, src/scss/components/prev-next-link.module.scss, src/scss/pages/blog/markdown.module.scss
=> 前後記事へのリンク追加

src/scss/pages/blog/markdown.module.scss
=> ブログにおける表のスタイルの追加

src/scss/_color.variable.scss
=> 暗いメインカラーをより暗く変更

src/components/header.tsx, src/components/layout.tsx, src/components/navigation.tsx, src/scss/components/header.module.scss, src/scss/components/navigation.module.scss
=> ヘッダーの簡素化とナビメニューの追加

.github/CODEOWNERS
=> SCSS ファイルのコードオーナーの変更

.github/workflows/ci.yml
=> Stop dispatching deploy job

src/scss/components/navigation.module.scss
Reverts approvers/site#202.
間違った修正でした.
=> Revert "SCSS の data-showing 指定の修正"

src/scss/_details.variable.scss, src/scss/components/avatar.module.scss, src/scss/components/paper.module.scss, src/scss/pages/blog.module.scss, src/scss/pages/member.module.scss
=> メンバーリストのスタイルの修正

src/pages/404.tsx, src/scss/pages/404.module.scss
=> HTTP 404のページを追加

src/scss/_media.variable.scss
=> fix: Fix media query

src/components/header.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/scss/components/header.module.scss, src/scss/global.scss
Lighthouse のパフォーマンス項目が緑色になるのを目指します.
=> パフォーマンスの改善

src/components/__snapshots__/footer.test.tsx.snap, src/components/__snapshots__/header.test.tsx.snap, src/components/__snapshots__/layout.test.tsx.snap, src/components/__snapshots__/navigation.test.tsx.snap, src/components/__snapshots__/prev-next-link.test.tsx.snap, src/components/__snapshots__/sns-link.test.tsx.snap, src/components/__snapshots__/title.test.tsx.snap, src/components/footer.tsx, src/components/header.tsx, src/pages/blog.tsx
=> ボーダー線幅の指定の修正

data/blogs/001.md, data/blogs/002.md, src/lib/blog-fetch.ts, src/pages/blog.tsx, src/pages/blog/[id].tsx
[site-data 側のデータ変更](https://github.com/approvers/site-data/pull/64) のマージ待ちです.
=> feat: 著者名を GitHub のリンクへと変更

package.json, yarn.lock
依存関係をリファクタしました。
- `react-image`は未使用のため、削除しました
- `sass`は`devDependencies`へ移動しました
=> chore: Refactor dependencies

src/pages/index.tsx, src/scss/pages/index.module.scss
=> feat: Change triangle into カス

.eslintrc, package.json, src/pages/blog.tsx, yarn.lock
- fix: Remove needless anchor element from next/link
- Fix lock file
- Update linter
=> fix: Remove needless anchor and Fix build scripts

.yarn/sdks/eslint/package.json, .yarn/sdks/prettier/index.js, .yarn/sdks/prettier/package.json, .yarn/sdks/typescript/lib/tsserver.js, .yarn/sdks/typescript/lib/tsserverlibrary.js, .yarn/sdks/typescript/package.json, src/components/sns-link.tsx, src/lib/member-fetch.ts, src/pages/member.tsx
- Update type validation
- Support new format
- Fix validation bug
=> feat: Switch members data source to members-assoc

src/app/layout.tsx
=> fix: themeColor の設定を viewport へ移動

gatsby-config.ts, package.json, pnpm-lock.yaml, src/components/header.tsx, src/components/link.tsx, src/components/navigation.tsx, src/components/providers.tsx, src/components/questions.tsx, src/components/sns-link.tsx, src/lib/theme.ts, src/pages/blog.tsx, src/pages/index.tsx, src/pages/link.tsx, src/pages/member.tsx, src/pages/policy.tsx, src/scss/pages/blog/markdown.module.scss, src/scss/pages/index.module.scss, src/templates/blog-post.tsx, src/utils/color-mode.tsx, tsconfig.json
- **Migrate dependencies**
- **Migrate base utils**
- **Migrate components**
- **Fix ThemeChangeButton**
- **Add Link to bring back external links**
=> fix: Fix theme corruption

src/components/header.tsx, src/components/link.tsx, src/pages/404.tsx, src/pages/blog.tsx, src/pages/index.tsx, src/pages/member.tsx, src/pages/policy.tsx
- **Fix avatar setting**
- **Migrate attributes**
- **Fix components**
=> fix: Migrate broken attributes
